import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "THE REAL CHAT",
  description: "Generated by THE REAL CHAT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="bg-[url(/BG.jpg)] bg-cover bg-[50%] bg-no-repeat min-h-screen w-screen overflow-x-hidden">
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
